### ISSUE TITLE
感觉这个库集成的东西太多，应该划分子模块

### ISSUE THREAD

**Issue by arden** [uxyheaven/XYQuickDevelop#4]
这个库感觉非常好，但是东西太多了，有时候不想引用这么多东西，应该对其进行模块划分。

**Comment by uxyheaven** [comment]
之前也想过多拆分几个项目出来, 
后来发现,集成的时候可以按照子模块集成, 基本上依赖不多.
如依赖的时候写 XYQuick/模块名
